# FONT
FONT = "Roboto"
SMALL = 20
NORMAL = 34
LARGE = 55
TITLE = 36

CORNER_RADIUS = 10

# COLORS # light # dark
PRIMARY = ("#f2f2f2", "#262626")
GREY = ("#f2f2f2", "#4d4d4d")
BLUE = ("#008080", "#00a3cc")
ACCENTGREY = ("#a6a6a6", "#a6a6a6")
WHITE = ("#262626", "#f2f2f2")
# BUTTON
BUTTON = {
    "AC": {
        "row": 0,
        "col": 0,
        "colspan": 2,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "(": {
        "row": 0,
        "col": 2,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    ")": {
        "row": 0,
        "col": 3,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "7": {
        "row": 1,
        "col": 0,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "8": {
        "row": 1,
        "col": 1,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "9": {
        "row": 1,
        "col": 2,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "4": {
        "row": 2,
        "col": 0,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "5": {
        "row": 2,
        "col": 1,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "6": {
        "row": 2,
        "col": 2,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "1": {
        "row": 3,
        "col": 0,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "2": {
        "row": 3,
        "col": 1,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "3": {
        "row": 3,
        "col": 2,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "0": {
        "row": 4,
        "col": 0,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "+": {
        "row": 1,
        "col": 3,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "-": {
        "row": 2,
        "col": 3,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "x": {
        "row": 4,
        "col": 3,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "/": {
        "row": 3,
        "col": 3,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "√": {
        "row": 2,
        "col": 4,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "x²": {
        "row": 1,
        "col": 4,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "Del": {
        "row": 0,
        "col": 4,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    ".": {
        "row": 4,
        "col": 2,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "=": {
        "row": 3,
        "col": 4,
        "colspan": 1,
        "rowspan": 2,
        "hv_color": GREY,
        "color": BLUE,
    },
    "E": {
        "row": 4,
        "col": 1,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
}

SCIENTIFIC_BUTTON = {
    "AC": {
        "row": 0,
        "col": 3,
        "colspan": 1,
        "rowspan": 2,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "(": {
        "row": 4,
        "col": 1,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    ")": {
        "row": 4,
        "col": 2,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "7": {
        "row": 5,
        "col": 0,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "8": {
        "row": 5,
        "col": 1,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "9": {
        "row": 5,
        "col": 2,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "4": {
        "row": 6,
        "col": 0,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "5": {
        "row": 6,
        "col": 1,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "6": {
        "row": 6,
        "col": 2,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "1": {
        "row": 7,
        "col": 0,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "2": {
        "row": 7,
        "col": 1,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "3": {
        "row": 7,
        "col": 2,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "0": {
        "row": 8,
        "col": 0,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "+": {
        "row": 4,
        "col": 3,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "-": {
        "row": 5,
        "col": 3,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "x": {
        "row": 6,
        "col": 3,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "/": {
        "row": 7,
        "col": 3,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "x²": {
        "row": 2,
        "col": 3,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "Del": {
        "row": 4,
        "col": 0,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    ".": {
        "row": 8,
        "col": 1,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "=": {
        "row": 8,
        "col": 3,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": BLUE,
    },
    "ln": {
        "row": 0,
        "col": 2,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "log": {
        "row": 0,
        "col": 1,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "sin/sin⁻¹": {
        "row": 1,
        "col": 0,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "cos/cos⁻¹": {
        "row": 1,
        "col": 1,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "tan/tan⁻¹": {
        "row": 1,
        "col": 2,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "SHIFT": {
        "row": 0,
        "col": 0,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    # "e":{"row":4, "col":1, "colspan": 1, "rowspan": 1, "hv_color": ACCENTGREY, "color" :GREY},
    "x!": {
        "row": 3,
        "col": 0,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    # "∛":{"row":4, "col":1, "colspan": 1, "rowspan": 1, "hv_color": ACCENTGREY, "color" :GREY},
    "^": {
        "row": 3,
        "col": 1,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "𝛑/x": {
        "row": 3,
        "col": 2,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "sinh": {
        "row": 2,
        "col": 0,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "cosh": {
        "row": 2,
        "col": 1,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "tanh": {
        "row": 2,
        "col": 2,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "x³/∛": {
        "row": 3,
        "col": 3,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
    "E/Ans": {
        "row": 8,
        "col": 2,
        "colspan": 1,
        "rowspan": 1,
        "hv_color": ACCENTGREY,
        "color": GREY,
    },
}
